### ISSUE TITLE
[question] Can i chang the password box and hide the button of unlock?

### ISSUE THREAD

**Issue by knm100** [jovanlanik/gtklock#112]
I would like to get a smaller passwd box and hide the button of unlock and the word of password.  what should I add to css file to   implementa it?
![swappy-20241106-182021](https://github.com/user-attachments/assets/0a9cc664-3a8a-4f64-9ab0-6f5bc1a07cd0)

**Comment by knm100** [comment]
I have been shorten the length of the password box.
by commenting out something of xml file, I can hide the button of unlock and the word of password with some GTK Warring.
I should do something more to remove these warnings.

I would like to chang the blue background of the botton to the other color, I've tried a lot of CSS Node names like #unlock-botton, #unlock-botton image, but there doesn't seem to be a way to change it.

**Comment by jovanlanik** [comment]
Can you show the gtk warnings you get?

**Comment by jovanlanik** [comment]
Also to change the button color use this css:
```css
#unlock-button {
    background-image: none;
    background-color: red;
}
```

**Comment by knm100** [comment]
> Can you show the gtk warnings you get?


The gtk warnings is as follows
[gtk-warnings.txt](https://github.com/user-attachments/files/17703475/gtk-warnings.txt)

This is my xml file
[gtklockui.xml.txt](https://github.com/user-attachments/files/17703491/gtklockui.xml.txt)

**Comment by jovanlanik** [comment]
Use this:
```css
#input-field:focus {
    border-color: darkred;
    box-shadow: 0 0 0 1px crimson;
}
```
