### ISSUE TITLE
per monitor background image

### ISSUE THREAD

**Issue by Hippo0o** [jovanlanik/gtklock#16]
Is there a way to define a background image per monitor? 
Like so in css: `window#DP-1 {}` or `window.HDMI-A-1 {}`

Or a way for a single background to span across monitors. So you could do smth like this:
```shell
grim /tmp/lock.png
corrupter -mag 1 -boffset 3 -meanabber 1 /tmp/lock.png /tmp/lock.png
gtklock -s style.css
```

**Comment by jovanlanik** [comment]
It wouldn't be too hard to implement per monitor bg, I'll get to it.
A span of a single image would require implementing custom drawing of backgrounds. Maybe taking a screenshot of every monitor separately would work?

**Comment by Hippo0o** [comment]
Per monitor background would  have more practical use i'd imagine, although more configuration.

I don't mind taking screenshots per monitor :)

**Comment by jovanlanik** [comment]
I added monitor names to windows so you can set backgrounds per monitor now using css. The only issue is that GTK doesn't offer an api to access output names such as DP-1 and HDMI-A-1 (used to but it's deprecated) so I'm using monitor model names instead. You can list out connected monitors by running `$ gtklock --list-monitors`

**Comment by ErikReider** [comment]
The needed GDK method isn't publicly visible ([gdk_monitor_get_connector](https://github.com/GNOME/gtk/blob/a2c54c739ed08eac6d360cd3a6ae140e1fab556d/gdk/gdkmonitorprivate.h#L63)).

The method for getting the connection name is deprecated ([gdk_screen_get_monitor_plug_name](https://github.com/GNOME/gtk/blob/a2c54c739ed08eac6d360cd3a6ae140e1fab556d/gdk/gdkscreen.c#L798-L827)) in favor of [gdk_monitor_get_model](https://github.com/GNOME/gtk/blob/a2c54c739ed08eac6d360cd3a6ae140e1fab556d/gdk/gdkmonitor.c#L395-L409) which doesn't even return the connection name, it returns the model. I'd use the deprecated option. It's not like GTK3 is getting updated with breaking features/updates right?

Maybe we should open an issue or even a MR about this?

**Comment by jovanlanik** [comment]
Yeah, you're right. I added use of the deprecated function and a pragma to hide the compiler warning.
I do hope the issue gets resolved on GTK's end.

Per monitor background are now possible using a CSS selector such as `window#HDMI-A-1`.

**Comment by Hippo0o** [comment]
Here is an example of how i use it now. 
@jovanlanik tyvm for the implementation :heart: 

lock.sh
```shell
#! /bin/bash
outputs=(HDMI-A-2 DP-1 eDP-1)

for o in ${outputs[@]}; do
    grim -o $o /tmp/$o.png
    corrupter -mag 1 -boffset 3 -meanabber 5 /tmp/$o.png /tmp/$o.png &
done

wait < <(jobs -p)

gtklock -d -s ~/.config/gtklock/style.css
```
style.css
```css
window {
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center;
    background-color: black;
}
window#HDMI-A-2 {
    background-image: url("/tmp/HDMI-A-2.png");
}
window#DP-1 {
    background-image: url("/tmp/DP-1.png");
}
window#eDP-1 {
    background-image: url("/tmp/eDP-1.png");
}
```
