### ISSUE TITLE
When using -b (background) the image should fill the screen

### ISSUE THREAD

**Issue by bhepple** [jovanlanik/gtklock#2]
So I'll be the second issue too!

I tried using the -b background option with an image smaller than my display and it put the image in the top left corner, leaving the rest of the screen exposed.

It would be nice if it added black bars to fill in the screen or shrunk the image if it were larger than the display - like 'imv -f' - see image 
![dump](https://user-images.githubusercontent.com/6417002/169233787-75676442-6ae9-4c31-af18-681a633be2f9.png)

EDIT: I figured out how to do a screendump of the locked screen:
![dump](https://user-images.githubusercontent.com/6417002/169235375-b1f442bd-3169-4040-8bfc-1aa87a0f76d1.png)

**Comment by jovanlanik** [comment]
Thank you for reporting this! I think I'll remove the background option completely...

If you want to set a background you can use css:
```css
window {
   background-image: url("image.png");
   background-size: contain;
   background-repeat: no-repeat;
   background-position: center;
   background-color: black;
}
```
